/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoToMp3RouteImport } from './routes/video-to-mp3'
import { Route as VideoToGifRouteImport } from './routes/video-to-gif'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResizeImageRouteImport } from './routes/resize-image'
import { Route as PngToJpgRouteImport } from './routes/png-to-jpg'
import { Route as Mp3CutterRouteImport } from './routes/mp3-cutter'
import { Route as JpgToPngRouteImport } from './routes/jpg-to-png'
import { Route as ImageCompressorRouteImport } from './routes/image-compressor'
import { Route as CropImageRouteImport } from './routes/crop-image'
import { Route as ToolIdRouteImport } from './routes/$toolId'
import { Route as IndexRouteImport } from './routes/index'

const VideoToMp3Route = VideoToMp3RouteImport.update({
  id: '/video-to-mp3',
  path: '/video-to-mp3',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoToGifRoute = VideoToGifRouteImport.update({
  id: '/video-to-gif',
  path: '/video-to-gif',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResizeImageRoute = ResizeImageRouteImport.update({
  id: '/resize-image',
  path: '/resize-image',
  getParentRoute: () => rootRouteImport,
} as any)
const PngToJpgRoute = PngToJpgRouteImport.update({
  id: '/png-to-jpg',
  path: '/png-to-jpg',
  getParentRoute: () => rootRouteImport,
} as any)
const Mp3CutterRoute = Mp3CutterRouteImport.update({
  id: '/mp3-cutter',
  path: '/mp3-cutter',
  getParentRoute: () => rootRouteImport,
} as any)
const JpgToPngRoute = JpgToPngRouteImport.update({
  id: '/jpg-to-png',
  path: '/jpg-to-png',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageCompressorRoute = ImageCompressorRouteImport.update({
  id: '/image-compressor',
  path: '/image-compressor',
  getParentRoute: () => rootRouteImport,
} as any)
const CropImageRoute = CropImageRouteImport.update({
  id: '/crop-image',
  path: '/crop-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolIdRoute = ToolIdRouteImport.update({
  id: '/$toolId',
  path: '/$toolId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$toolId': typeof ToolIdRoute
  '/crop-image': typeof CropImageRoute
  '/image-compressor': typeof ImageCompressorRoute
  '/jpg-to-png': typeof JpgToPngRoute
  '/mp3-cutter': typeof Mp3CutterRoute
  '/png-to-jpg': typeof PngToJpgRoute
  '/resize-image': typeof ResizeImageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/video-to-gif': typeof VideoToGifRoute
  '/video-to-mp3': typeof VideoToMp3Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$toolId': typeof ToolIdRoute
  '/crop-image': typeof CropImageRoute
  '/image-compressor': typeof ImageCompressorRoute
  '/jpg-to-png': typeof JpgToPngRoute
  '/mp3-cutter': typeof Mp3CutterRoute
  '/png-to-jpg': typeof PngToJpgRoute
  '/resize-image': typeof ResizeImageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/video-to-gif': typeof VideoToGifRoute
  '/video-to-mp3': typeof VideoToMp3Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$toolId': typeof ToolIdRoute
  '/crop-image': typeof CropImageRoute
  '/image-compressor': typeof ImageCompressorRoute
  '/jpg-to-png': typeof JpgToPngRoute
  '/mp3-cutter': typeof Mp3CutterRoute
  '/png-to-jpg': typeof PngToJpgRoute
  '/resize-image': typeof ResizeImageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/video-to-gif': typeof VideoToGifRoute
  '/video-to-mp3': typeof VideoToMp3Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$toolId'
    | '/crop-image'
    | '/image-compressor'
    | '/jpg-to-png'
    | '/mp3-cutter'
    | '/png-to-jpg'
    | '/resize-image'
    | '/sitemap.xml'
    | '/video-to-gif'
    | '/video-to-mp3'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$toolId'
    | '/crop-image'
    | '/image-compressor'
    | '/jpg-to-png'
    | '/mp3-cutter'
    | '/png-to-jpg'
    | '/resize-image'
    | '/sitemap.xml'
    | '/video-to-gif'
    | '/video-to-mp3'
  id:
    | '__root__'
    | '/'
    | '/$toolId'
    | '/crop-image'
    | '/image-compressor'
    | '/jpg-to-png'
    | '/mp3-cutter'
    | '/png-to-jpg'
    | '/resize-image'
    | '/sitemap.xml'
    | '/video-to-gif'
    | '/video-to-mp3'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolIdRoute: typeof ToolIdRoute
  CropImageRoute: typeof CropImageRoute
  ImageCompressorRoute: typeof ImageCompressorRoute
  JpgToPngRoute: typeof JpgToPngRoute
  Mp3CutterRoute: typeof Mp3CutterRoute
  PngToJpgRoute: typeof PngToJpgRoute
  ResizeImageRoute: typeof ResizeImageRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VideoToGifRoute: typeof VideoToGifRoute
  VideoToMp3Route: typeof VideoToMp3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-to-mp3': {
      id: '/video-to-mp3'
      path: '/video-to-mp3'
      fullPath: '/video-to-mp3'
      preLoaderRoute: typeof VideoToMp3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-to-gif': {
      id: '/video-to-gif'
      path: '/video-to-gif'
      fullPath: '/video-to-gif'
      preLoaderRoute: typeof VideoToGifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resize-image': {
      id: '/resize-image'
      path: '/resize-image'
      fullPath: '/resize-image'
      preLoaderRoute: typeof ResizeImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/png-to-jpg': {
      id: '/png-to-jpg'
      path: '/png-to-jpg'
      fullPath: '/png-to-jpg'
      preLoaderRoute: typeof PngToJpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mp3-cutter': {
      id: '/mp3-cutter'
      path: '/mp3-cutter'
      fullPath: '/mp3-cutter'
      preLoaderRoute: typeof Mp3CutterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jpg-to-png': {
      id: '/jpg-to-png'
      path: '/jpg-to-png'
      fullPath: '/jpg-to-png'
      preLoaderRoute: typeof JpgToPngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-compressor': {
      id: '/image-compressor'
      path: '/image-compressor'
      fullPath: '/image-compressor'
      preLoaderRoute: typeof ImageCompressorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-image': {
      id: '/crop-image'
      path: '/crop-image'
      fullPath: '/crop-image'
      preLoaderRoute: typeof CropImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$toolId': {
      id: '/$toolId'
      path: '/$toolId'
      fullPath: '/$toolId'
      preLoaderRoute: typeof ToolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolIdRoute: ToolIdRoute,
  CropImageRoute: CropImageRoute,
  ImageCompressorRoute: ImageCompressorRoute,
  JpgToPngRoute: JpgToPngRoute,
  Mp3CutterRoute: Mp3CutterRoute,
  PngToJpgRoute: PngToJpgRoute,
  ResizeImageRoute: ResizeImageRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VideoToGifRoute: VideoToGifRoute,
  VideoToMp3Route: VideoToMp3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
