/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordToolsRouteImport } from './routes/word-tools'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResizeImageRouteImport } from './routes/resize-image'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PngToJpgRouteImport } from './routes/png-to-jpg'
import { Route as NetworkToolsRouteImport } from './routes/network-tools'
import { Route as Mp3CutterRouteImport } from './routes/mp3-cutter'
import { Route as JpgToPngRouteImport } from './routes/jpg-to-png'
import { Route as ImageCompressorRouteImport } from './routes/image-compressor'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DeveloperToolsRouteImport } from './routes/developer-tools'
import { Route as CropImageRouteImport } from './routes/crop-image'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ToolIdRouteImport } from './routes/$toolId'
import { Route as IndexRouteImport } from './routes/index'

const WordToolsRoute = WordToolsRouteImport.update({
  id: '/word-tools',
  path: '/word-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResizeImageRoute = ResizeImageRouteImport.update({
  id: '/resize-image',
  path: '/resize-image',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PngToJpgRoute = PngToJpgRouteImport.update({
  id: '/png-to-jpg',
  path: '/png-to-jpg',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkToolsRoute = NetworkToolsRouteImport.update({
  id: '/network-tools',
  path: '/network-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const Mp3CutterRoute = Mp3CutterRouteImport.update({
  id: '/mp3-cutter',
  path: '/mp3-cutter',
  getParentRoute: () => rootRouteImport,
} as any)
const JpgToPngRoute = JpgToPngRouteImport.update({
  id: '/jpg-to-png',
  path: '/jpg-to-png',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageCompressorRoute = ImageCompressorRouteImport.update({
  id: '/image-compressor',
  path: '/image-compressor',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperToolsRoute = DeveloperToolsRouteImport.update({
  id: '/developer-tools',
  path: '/developer-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const CropImageRoute = CropImageRouteImport.update({
  id: '/crop-image',
  path: '/crop-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolIdRoute = ToolIdRouteImport.update({
  id: '/$toolId',
  path: '/$toolId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$toolId': typeof ToolIdRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/crop-image': typeof CropImageRoute
  '/developer-tools': typeof DeveloperToolsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/image-compressor': typeof ImageCompressorRoute
  '/jpg-to-png': typeof JpgToPngRoute
  '/mp3-cutter': typeof Mp3CutterRoute
  '/network-tools': typeof NetworkToolsRoute
  '/png-to-jpg': typeof PngToJpgRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resize-image': typeof ResizeImageRoute
  '/terms': typeof TermsRoute
  '/word-tools': typeof WordToolsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$toolId': typeof ToolIdRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/crop-image': typeof CropImageRoute
  '/developer-tools': typeof DeveloperToolsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/image-compressor': typeof ImageCompressorRoute
  '/jpg-to-png': typeof JpgToPngRoute
  '/mp3-cutter': typeof Mp3CutterRoute
  '/network-tools': typeof NetworkToolsRoute
  '/png-to-jpg': typeof PngToJpgRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resize-image': typeof ResizeImageRoute
  '/terms': typeof TermsRoute
  '/word-tools': typeof WordToolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$toolId': typeof ToolIdRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/crop-image': typeof CropImageRoute
  '/developer-tools': typeof DeveloperToolsRoute
  '/disclaimer': typeof DisclaimerRoute
  '/image-compressor': typeof ImageCompressorRoute
  '/jpg-to-png': typeof JpgToPngRoute
  '/mp3-cutter': typeof Mp3CutterRoute
  '/network-tools': typeof NetworkToolsRoute
  '/png-to-jpg': typeof PngToJpgRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/resize-image': typeof ResizeImageRoute
  '/terms': typeof TermsRoute
  '/word-tools': typeof WordToolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$toolId'
    | '/about'
    | '/contact'
    | '/crop-image'
    | '/developer-tools'
    | '/disclaimer'
    | '/image-compressor'
    | '/jpg-to-png'
    | '/mp3-cutter'
    | '/network-tools'
    | '/png-to-jpg'
    | '/privacy-policy'
    | '/resize-image'
    | '/terms'
    | '/word-tools'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$toolId'
    | '/about'
    | '/contact'
    | '/crop-image'
    | '/developer-tools'
    | '/disclaimer'
    | '/image-compressor'
    | '/jpg-to-png'
    | '/mp3-cutter'
    | '/network-tools'
    | '/png-to-jpg'
    | '/privacy-policy'
    | '/resize-image'
    | '/terms'
    | '/word-tools'
  id:
    | '__root__'
    | '/'
    | '/$toolId'
    | '/about'
    | '/contact'
    | '/crop-image'
    | '/developer-tools'
    | '/disclaimer'
    | '/image-compressor'
    | '/jpg-to-png'
    | '/mp3-cutter'
    | '/network-tools'
    | '/png-to-jpg'
    | '/privacy-policy'
    | '/resize-image'
    | '/terms'
    | '/word-tools'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolIdRoute: typeof ToolIdRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CropImageRoute: typeof CropImageRoute
  DeveloperToolsRoute: typeof DeveloperToolsRoute
  DisclaimerRoute: typeof DisclaimerRoute
  ImageCompressorRoute: typeof ImageCompressorRoute
  JpgToPngRoute: typeof JpgToPngRoute
  Mp3CutterRoute: typeof Mp3CutterRoute
  NetworkToolsRoute: typeof NetworkToolsRoute
  PngToJpgRoute: typeof PngToJpgRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResizeImageRoute: typeof ResizeImageRoute
  TermsRoute: typeof TermsRoute
  WordToolsRoute: typeof WordToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/word-tools': {
      id: '/word-tools'
      path: '/word-tools'
      fullPath: '/word-tools'
      preLoaderRoute: typeof WordToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resize-image': {
      id: '/resize-image'
      path: '/resize-image'
      fullPath: '/resize-image'
      preLoaderRoute: typeof ResizeImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/png-to-jpg': {
      id: '/png-to-jpg'
      path: '/png-to-jpg'
      fullPath: '/png-to-jpg'
      preLoaderRoute: typeof PngToJpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network-tools': {
      id: '/network-tools'
      path: '/network-tools'
      fullPath: '/network-tools'
      preLoaderRoute: typeof NetworkToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mp3-cutter': {
      id: '/mp3-cutter'
      path: '/mp3-cutter'
      fullPath: '/mp3-cutter'
      preLoaderRoute: typeof Mp3CutterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jpg-to-png': {
      id: '/jpg-to-png'
      path: '/jpg-to-png'
      fullPath: '/jpg-to-png'
      preLoaderRoute: typeof JpgToPngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-compressor': {
      id: '/image-compressor'
      path: '/image-compressor'
      fullPath: '/image-compressor'
      preLoaderRoute: typeof ImageCompressorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer-tools': {
      id: '/developer-tools'
      path: '/developer-tools'
      fullPath: '/developer-tools'
      preLoaderRoute: typeof DeveloperToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-image': {
      id: '/crop-image'
      path: '/crop-image'
      fullPath: '/crop-image'
      preLoaderRoute: typeof CropImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$toolId': {
      id: '/$toolId'
      path: '/$toolId'
      fullPath: '/$toolId'
      preLoaderRoute: typeof ToolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolIdRoute: ToolIdRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CropImageRoute: CropImageRoute,
  DeveloperToolsRoute: DeveloperToolsRoute,
  DisclaimerRoute: DisclaimerRoute,
  ImageCompressorRoute: ImageCompressorRoute,
  JpgToPngRoute: JpgToPngRoute,
  Mp3CutterRoute: Mp3CutterRoute,
  NetworkToolsRoute: NetworkToolsRoute,
  PngToJpgRoute: PngToJpgRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResizeImageRoute: ResizeImageRoute,
  TermsRoute: TermsRoute,
  WordToolsRoute: WordToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
